version: 0.2
env:
    variables:
      CACHE_CONTROL: "86400"
      S3_BUCKET: "{{s3_bucket_url}}"
      BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod --aot
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
