version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod --aot
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes